### ISSUE TITLE
erreur GLOBAL SETTING

### ISSUE THREAD

**Issue by samszo** [Daniel-KM/Omeka-S-module-Cartography#3]
Avec la dernière version du module dans la dernière version de omeka, l'activation du module Cartography crée une erreur quand on veut consulter la page admin/setting :
Doctrine\ORM\Query\QueryException
[Syntax Error] line 0, col 75: Error: Expected Doctrine\ORM\Query\Lexer::T_IDENTIFIER, got 'Omeka\Entity\ResourceTemplate'

**Comment by Daniel-KM** [comment]
Ok, je regarde. Je viens aussi de corriger un problème similaire dans Annotate.

**Comment by Daniel-KM** [comment]
Il faut mettre à jour aussi DataTypeGeometry. Je crois que c'est corrigé.

**Comment by samszo** [comment]
OK la mise à jour du module Annotate règle le problème
